version: '3.9'

services:
  mpt-frontend-container:
    build:
      context: ./frontend
    ports:
      - "${MPT_FRONTEND_CONTAINER_PORT}:${MPT_FRONTEND_CONTAINER_PORT}"
    env_file:
      - ./.env
    volumes:
      - ${MPT_SSL_FILES_PATH}:/usr/src/app/https/
    depends_on:
      - mpt-backend-container

  mpt-backend-container:
    build:
      context: ./backend
    ports:
      - "${MPT_BACKEND_CONTAINER_PORT}:${MPT_BACKEND_CONTAINER_PORT}"
    env_file:
      - ./.env
    volumes:
      - ${MPT_SSL_FILES_PATH}:/https/
      # - /c/temp-keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - mpt-database

  mpt-database:
    image: mcr.microsoft.com/mssql/server:2022-CU6-ubuntu-20.04
    user: root
    environment:
      - MSSQL_SA_PASSWORD=${MPT_DB_USER_PASSWORD}
      - ACCEPT_EULA=Y
    env_file:
      - ./.env
    ports:
      - "${MPT_DATABASE_CONTAINER_PORT}:${MPT_DATABASE_CONTAINER_PORT}"
    volumes:
      - ./db_data/data:/var/opt/mssql/data
      - ./db_data/log:/var/opt/mssql/log
      - ./db_data/secrets:/var/opt/mssql/secrets